#!/usr/bin/env python

"""
Copyright (c) 2006-2021 sqlmap developers (http://sqlmap.org/)
See the file 'LICENSE' for copying permission
"""

import random
import re

from lib.core.data import kb
from lib.core.datatype import OrderedSet
from lib.core.enums import PRIORITY

__priority__ = PRIORITY.NORMAL

def dependencies():
    pass

def tamper(payload, **kwargs):
    """
    Adds multiple spaces (' ') around SQL keywords

    Notes:
        * Useful to bypass very weak and bespoke web application firewalls
          that has poorly written permissive regular expressions

    Reference: https://www.owasp.org/images/7/74/Advanced_SQL_Injection.ppt

    >>> random.seed(0)
    >>> kb.keywords = {'CURRENT_CATALOG', 'SQL_SMALL_RESULT', 'ABS', 'XMLDOCUMENT', 'SYSTEM', 'UESCAPE', 'LOCALTIME', 'REGR_SXY', 'DEFAULTDELAYED', 'IS', 'BETWEEN', 'NORMALIZE', 'ZEROFILL', 'SYSTEM_USER', 'PERCENTILE_DISC', 'SPECIFIC', 'DETERMINISTIC', 'FLOAT', 'LOCK', 'ININDEX', 'REGR_INTERCEPT', 'XMLCOMMENT', 'PARAMETER', 'INPUT', 'NO', 'PROCEDURE', 'WINDOW', 'DECLARE', 'REGR_AVGY', 'CONTINUE', 'FROM', 'INT2', 'SET', 'START', 'XMLATTRIBUTES', 'SYMMETRIC', 'COUNT', 'NAMES', 'UNIQUEUNLOCK', 'YEAR_MONTH', 'ROUTINE', 'LIKE', 'DATALINK', 'GO', 'SQLCODE', 'XMLTEXT', 'PORTION', 'ARRAY_MAX_CARDINALITY', 'NTH_VALUE', 'CALLED', 'ONE', 'RELEASE', 'IMMEDIATE', 'NULLIF', 'MIN', 'XMLEXISTS', 'GRANT', 'TRIM_ARRAY', 'REGR_SXX', 'WITH', 'WHILE', 'XMLVALIDATE', 'ILIKE', 'COALESCE', 'VALUE', 'MEDIUMTEXTMIDDLEINT', 'STDDEV_SAMP', 'EXPLAIN', 'DEFERRABLE', 'CURRENT_DEFAULT_TRANSFORM_GROUP', 'ROLLBACK', 'MEASURES', 'DISCONNECT', 'RENAME', 'KEY', 'INSERT', 'COMMIT', 'CURRENT', 'CEILING', 'ROLLUP', 'ARE', 'HANDLER', 'UNTIL', 'SMALLINTSONAME', 'LN', 'MINUTE_SECOND', 'TRUNCATE', 'COLUMN', 'LOWER', 'FILTER', 'TRIGGER', 'END', 'XML', 'BEGIN_FRAME', 'OUTFILE', 'OUTPUT', 'PURGE', 'ONLY', 'USE', 'DEFERRED', 'DEALLOCATE', 'SUCCEEDS', 'DLURLCOMPLETEONLY', 'ANALYSE', 'CYCLE', 'NOT', 'RESIGNAL', 'SPACE', 'JSON_TABLE_PRIMITIVE', 'HIGH_PRIORITYHOUR_MICROSECOND', 'ON', 'DLURLSCHEME', 'CHAR_LENGTH', 'EXISTS', 'IN', 'INTEGER', 'CUBE', 'XMLCAST', 'WRITE', 'UNSIGNED', 'ZONE', 'TINYTEXTTO', 'DLURLCOMPLETEWRITE', 'MEMBER', 'HOUR_MINUTE', 'KEYS', 'TAN', 'LOCALTIMESTAMP', 'ROW', 'REALREFERENCES', 'PERMUTE', 'EQUALS', 'CATALOG', 'TABLE', 'OPEN', 'WHENEVER', 'JSON_EXISTS', 'INTERVALINTO', 'CONSTRAINT', 'CARDINALITY', 'POSITION', 'LOW_PRIORITY', 'WRITEXOR', 'MAX', 'PRECISIONPRIMARY', 'EACH', 'ISOLATION', 'RUNNING', 'CASE', 'OVER', 'INT4', 'VARCHARACTERVARYING', 'VERSION', 'DIAGNOSTICS', 'UNIQUE', 'SESSION_USER', 'LEADING', 'IMPORT', 'SEEK', 'ELSE', 'SSL', 'EXECUTE', 'USAGE', 'STDDEV_POP', 'JSON_VALUE', 'JSON_ARRAY', 'NONE', 'MATCH', 'PLACING', 'BIT', 'CREATE', 'IGNORE', 'XMLITERATE', 'DEFINE', 'MODIFIES', 'AS', 'STARTINGSTRAIGHT_JOIN', 'SUBSET', 'LOCAL', 'VARIADIC', 'HAVING', 'DAY', 'CASECHANGE', 'DLURLPATH', 'FREE', 'JSON_ARRAYAGG', 'PERCENTILE_CONT', 'METHOD', 'JOIN', 'DECFLOAT', 'EXTRACT', 'REGR_COUNT', 'ASYMMETRIC', 'VERBOSE', 'INSENSITIVE', 'PERCENT_RANK', 'ITERATE', 'REAL', 'SPECIFICTYPE', 'EXP', 'SIGNAL', 'SCROLL', 'BEFORE', 'ESCAPED', 'JSON_OBJECTAGG', 'DYNAMIC', 'UNMATCHED', 'PRIMARY', 'VAR_POP', 'CONTAINS', 'XMLBINARY', 'JSON_OBJECT', 'LOOP', 'CURRENT_ROW', 'YEAR', 'OPTIONALLYOR', 'SECOND', 'THEN', 'SYSTEM_TIME', 'OPTIMIZE', 'TIMEZONE_HOUR', 'SIZE', 'READ', 'SENSITIVE', 'CONVERT', 'ALLOCATE', 'WIDTH_BUCKET', 'VALUES', 'INTERSECTION', 'HOUR_SECOND', 'ELSEIF', 'SCHEMA', 'MATCH_NUMBER', 'DECIMAL', 'VARYING', 'PATH', 'INTERSECT', 'FALSEFETCH', 'VAR_SAMP', 'CASCADED', 'XMLPARSE', 'REFERENCING', 'DIV', 'DAY_SECOND', 'FLOAT4', 'CONSTRAINTS', 'LOG10', 'ACTION', 'DOUBLE', 'ASIN', 'FREEZE', 'TABLESAMPLE', 'TO', 'TERMINATED', 'VALUE_OF', 'DOMAIN', 'VERSIONING', 'SQL', 'CHECK', 'CURRENT_TIMESTAMP', 'LEAVE', 'TIMESTAMP', 'NEW', 'RETURNING', 'REGR_SYY', 'WHEN', 'BY', 'ELSEELSEIF', 'TINYBLOB', 'CURRENT_TRANSFORM_GROUP_FOR_TYPE', 'NOTNULL', 'IDENTITY', 'LEVEL', 'COSH', 'OFFSET', 'SUBSTRING', 'BINARY', 'DO', 'RETURNS', 'LAST', 'JSON_TABLE', 'FOREIGN', 'ASC', 'EXTERNAL', 'CASCADE', 'SQLWARNING', 'LANGUAGE', 'CHAR', 'ADD', 'XMLCONCAT', 'ATAN', 'GROUP', 'SAVEPOINT', 'UNNEST', 'INTERVAL', 'SIN', 'LATERAL', 'SPATIAL', 'MULTISET', 'SQLEXCEPTION', 'CURRENT_TIME', 'CHARACTER', 'COLLATION', 'UNKNOWN', 'PRECEDES', 'AUTHORIZATION', 'FORCE', 'COVAR_POP', 'DATE', 'ELEMENT', 'SQLERROR', 'SHOW', 'REPEAT', 'FIRST', 'CURSOR', 'GOTO', 'MEDIUMINT', 'DISTINCT', 'FULLTEXT', 'PRIOR', 'PERCENT', 'REPLACE', 'LINESLOAD', 'ENCLOSED', 'CHARACTER_LENGTH', 'BEGIN_PARTITION', 'NEXT', 'BIT_LENGTH', 'END_PARTITION', 'DESC', 'RECURSIVE', 'SCOPE', 'STATIC', 'NUMERIC', 'REGR_R2', 'CONCURRENTLY', 'DAY_HOUR', 'DLVALUE', 'CONNECT', 'NATIONAL', 'SELECT', 'ATOMIC', 'REFERENCES', 'MINUTE', 'INNER', 'DENSE_RANK', 'OLD', 'EXCEPT', 'READS', 'SINH', 'ORDER', 'SKIP', 'INT3', 'WITHOUT', 'CONDITION', 'RLIKE', 'COLLECT', 'CEIL', 'GROUPS', 'RANGE', 'WORK', 'COVAR_SAMP', 'ACOS', 'MOD', 'LOG', 'XMLAGG', 'XMLSERIALIZE', 'ABSOLUTE', 'ISNULL', 'SQLSTATESQLWARNING', 'LEFT', 'FRAME_ROW', 'INTO', 'POSITION_REGEX', 'BEGIN', 'CORRESPONDING', 'EXIT', 'SMALLINT', 'OCCURRENCES_REGEX', 'SUBMULTISET', 'SCHEMASSECOND_MICROSECOND', 'CLOSE', 'ANY', 'DEREF', 'SUM', 'PAD', 'DLURLCOMPLETE', 'SIMILAR', 'MEDIUMBLOB', 'DROP', 'EVERY', 'JSON_QUERY', 'LARGE', 'DLPREVIOUSCOPY', 'PRESERVE', 'KILLLEADING', 'DLNEWCOPY', 'BOOLEAN', 'AVG', 'MERGE', 'DLURLPATHONLY', 'TRANSACTION', 'GROUPING', 'BLOB', 'DEC', 'NCHAR', 'BINARYBLOB', 'HOLD', 'FETCH', 'CONCAT', 'CALL', 'DESCRIBE', 'OVERLAPS', 'VARCHAR', 'MATCH_RECOGNIZE', 'IF', 'VIEW', 'NTILE', 'ARRAY', 'ASENSITIVE', 'IFNULL', 'TRANSLATE', 'CONDITIONCONSTRAINT', 'INT8', 'LAST_VALUE', 'FALSE', 'DUAL', 'OVERLAY', 'INITIALLY', 'END_FRAME', 'PRECISION', 'RANK', 'SECTION', 'NULL', 'XMLFOREST', 'OR', 'CROSS', 'CURRENT_USER', 'CLOB', 'ARRAY_AGG', 'BOTH', 'INITIAL', 'LIMIT', 'UTC_TIMESTAMP', 'SEPARATOR', 'XMLELEMENT', 'OCTET_LENGTH', 'LONGBLOBLONGTEXT', 'HOUR', 'WITHIN', 'ASSERTION', 'CURRENT_PATH', 'EMPTY', 'XMLNAMESPACES', 'OMIT', 'BIGINT', 'AND', 'SQLSTATE', 'SQL_CALC_FOUND_ROWS', 'FUNCTION', 'CAST', 'ALL', 'ALTER', 'OUT', 'CONNECTION', 'XMLTABLE', 'TEMPORARY', 'CUME_DIST', 'VARBINARY', 'TRIM', 'PATTERN', 'USING', 'WHERE', 'GET', 'COS', 'END-EXEC', 'DATABASES', 'INDICATOR', 'MONTH', 'INTINT1', 'DELETE', 'CURRENT_ROLE', 'FUSION', 'LISTAGG', 'MATCHES', 'REGR_AVGX', 'DEFAULT', 'XMLQUERY', 'SESSION', 'USER', 'FOREIGNFROM', 'PARTIAL', 'PARTITION', 'PTF', 'PERIOD', 'UNDO', 'FULL', 'OUTER', 'LONG', 'SOME', 'CURRENT_SCHEMA', 'CLASSIFIER', 'DLURLSERVER', 'LEAD', 'ASASC', 'RESULT', 'FIRST_VALUE', 'PREPARE', 'EXCEPTION', 'UPDATE', 'UNION', 'RELATIVE', 'NCLOB', 'CURRENT_DATE', 'DESCRIPTOR', 'LAG', 'OF', 'TIMEZONE_MINUTE', 'TRUE', 'POWER', 'ANALYZE', 'COPY', 'MINUTE_MICROSECOND', 'FLOOR', 'TREAT', 'SQL_BIG_RESULT', 'AT', 'NOTNO_WRITE_TO_BINLOG', 'NATURAL', 'TIME', 'DATABASE', 'PRIVILEGES', 'PER', 'DISTINCTDISTINCTROW', 'REVOKE', 'FOUND', 'INT', 'FOR', 'CORR', 'REQUIRERESTRICT', 'CURRENT_TIMECURRENT_TIMESTAMP', 'INOUT', 'SUBSTRING_REGEX', 'EXEC', 'SEARCH', 'DAY_MICROSECONDDAY_MINUTE', 'FLOAT8', 'DLURLPATHWRITE', 'TRANSLATE_REGEX', 'ESCAPE', 'UPPER', 'REGEXP', 'UTC_DATEUTC_TIME', 'TANH', 'INFILE', 'RIGHT', 'TRAILING', 'OPTION', 'TINYINT', 'TRANSLATION', 'ROWS', 'ROW_NUMBER', 'REGR_SLOPE', 'RESTRICT', 'MODULE', 'SQRT', 'GLOBAL', 'RETURN', 'XMLPI', 'LIKE_REGEX', 'REF', 'COLLATE'}
    >>> tamper('1 UNION SELECT foobar')
    '1     UNION     SELECT     foobar'
    """

    retVal = payload

    if payload:
        words = OrderedSet()

        for match in re.finditer(r"\b[A-Za-z_]+\b", payload):
            word = match.group()

            if word.upper() in kb.keywords:
                words.add(word)

        for word in words:
            retVal = re.sub(r"(?<=\W)%s(?=[^A-Za-z_(]|\Z)" % word, "%s%s%s" % (' ' * random.randint(1, 4), word, ' ' * random.randint(1, 4)), retVal)
            retVal = re.sub(r"(?<=\W)%s(?=[(])" % word, "%s%s" % (' ' * random.randint(1, 4), word), retVal)

    return retVal
